### PR TITLE
wincng: fix multiple definition of `_libssh2_wincng'

### PR DESCRIPTION
**Pull request by mati865**
Fix for https://github.com/alexcrichton/ssh2-rs/issues/187

### CODE REVIEW

**Comment by mati865** [comment]
@wez could you review it?
ssh2-rs doesn't build for windows-gnu target without it.

**Comment by wez** [comment]
Sorry, I haven't had the opportunity to review this yet.
When I'm next in "windows mode" I plan to review https://github.com/libssh2/libssh2/pull/484 which may obviate this completely.
If you have a chance to try that PR with the rust crate I'd appreciate your feedback on how well that works!

**Comment by mati865** [comment]
libssh2#484 works because it's latest master.
My PR just backports single commit from the master.

**Comment by mati865** [comment]
@wez can I know when you are going to do the review? I don't know what to tell people asking me why `ssh2-rs` is broken on Tier 1 target.

**Comment by wez** [comment]
@mati865 The short answer is, when I get time and feel in the mood.

The longer answer is that I have a busy life with many competing priorities.  This is a grudging free time project: I don't really want to own anything to relating to ssh but I find myself with a couple of related forks because I could help push some things forward.  I'm not paid to work on this.  I don't generally develop on windows through choice.  Usually, if I have my windows system running, I want to blow off steam and play games on it.

I'm afraid I don't know who you are or why people are asking you about `ssh-rs`, or why you think you have the right to pressure me about how I am spending my free time.

My suggestion is to pin to `0.8.0` if that worked better, and to be patient.

**Comment by mati865** [comment]
@wez I apologize if that sounded harsh, that wasn't my intention.

> The longer answer is that I have a busy life with many competing priorities.

I understand that, I'll just tell to not expect the fix soon.

> I'm afraid I don't know who you are or why people are asking you about ssh-rs

Nobody important, people have noticed I've fixed few MinGW related Rust bugs.

> My suggestion is to pin to 0.8.0 if that worked better, and to be patient.

That's not easy with `cargo install`, guess I'll recommend to use `LIBSSH2_SYS_USE_PKG_CONFIG=1` for now.

**Comment by mati865** [comment]
Obsoleted by https://github.com/alexcrichton/ssh2-rs/commit/e8d4dc165fbcd3fceeec96db9d1e9be9b67bef7b

**Pull request closed without merging**
